# Automated Release Workflow
#
# This workflow automatically manages versioning and releases based on commit messages.
# It uses Conventional Commits to determine the version bump type.
# Uses reusable workflow from hope0hermes/SharedWorkflows for consistent CI/CD across projects.
#
# REQUIRED SECRET:
# - PAT_TOKEN: Personal Access Token with 'repo' and 'pull_requests' scopes
#   Create at: https://github.com/settings/tokens/new
#   Add to repo secrets at: https://github.com/hope0hermes/StravaFetcher/settings/secrets/actions
#
# When it runs:
# - Automatically: When a PR is merged to main (via "push: branches: [main]")
# - Manually: Via GitHub Actions UI (workflow_dispatch button)
#
# What it does:
# 1. Analyzes commit messages since last release
# 2. Determines version bump type (major/minor/patch/none)
# 3. Updates version in src/strava_fetcher/__init__.py using hatch
# 4. Updates CHANGELOG.md with new version and commit list
# 5. Creates a PR with version bump changes
# 6. After PR is merged, create-release.yml automatically creates the GitHub Release
#
# Conventional Commit Format → Version Bump:
# - "feat:" or "feature:" → MINOR bump (1.0.0 → 1.1.0) - New features
# - "fix:" or "bugfix:" → PATCH bump (1.0.0 → 1.0.1) - Bug fixes
# - "feat!:" or "BREAKING CHANGE:" → MAJOR bump (1.0.0 → 2.0.0) - Breaking changes
# - "chore:", "docs:", "ci:", "style:", "test:" → NO bump - No user-facing changes
#
# Version Management:
# - Version stored in: src/strava_fetcher/__init__.py (__version__ = "1.0.0")
# - Hatch reads/writes version automatically (configured in pyproject.toml)
# - Single source of truth prevents version conflicts

name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  release:
    uses: hope0hermes/SharedWorkflows/.github/workflows/reusable-release.yml@main
    with:
      package-path: "src/strava_fetcher/__init__.py"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}